from fastapi import APIRouter, Depends, HTTPException, Body
from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime
import random

from models import AIQuestionRequest, AIQuestionResponse
from watsonx_service import watsonx_service
from container import container

router = APIRouter(
    prefix="/tutor",
    tags=["tutor"]
)

@router.post("/chat", response_model=AIQuestionResponse)
async def chat_tutor(request: AIQuestionRequest):
    try:
        # Check if watsonx is configured
        if watsonx_service.api_key:
            # Placeholder for actual LLM call
            # In a real implementation: response = await watsonx_service.generate_text(request.question)
            answer = "WatsonX (Real): " + "Quantum superposition allows qubits to be in multiple states at once. (API Connected)"
        else:
             # Fallback simulation logic
             responses = [
                "That's a great question! Let me explain...",
                "In quantum mechanics, this works by...",
                "Good question. The key concept here is..."
             ]
             prefix = random.choice(responses)
             
             context = "Quantum computing differs from classical computing by using qubits."
             if "entanglement" in request.question.lower():
                 context = "Entanglement effectively links qubits such that the state of one is dependent on the other."
             elif "superposition" in request.question.lower():
                 context = "Superposition allows a qubit to be both 0 and 1 simultaneously with certain probabilities."
             elif "gate" in request.question.lower():
                 context = "Quantum gates are unitary operators that manipulate the state of qubits."
                 
             answer = f"{prefix}\n\n{context}\n\n(Generated by Backend Tutor Service)"
             
        return AIQuestionResponse(
             success=True,
             question=request.question,
             answer=answer,
             timestamp=datetime.utcnow().isoformat()
        )

    except Exception as e:
        container.logger().error("tutor_chat_failed", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))
